---
- name: Upload the config file
  copy:
    src: docker-compose.yaml
    dest: /root/webserver/docker-compose.yaml
    owner: root
    group: root
    mode: 0644
  become: true

- name: Upload the config file
  copy:
    src: index.html
    dest: /root/github/eindopdracht/index.html
    owner: root
    group: root
    mode: 0755
  become: true

- name: Upload the config file
  copy:
    src: todo_list.php
    dest: /root/github/eindopdracht/todo_list.php
    owner: root
    group: root
    mode: 0755
  become: true
