---
- name: Add Ondřej Surý's PHP PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install Apache2
  apt:
    name: apache2
    state: present

- name: Install PHP 8.2 and required extensions
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - php8.2
    - libapache2-mod-php8.2
    - php8.2-common
    - php8.2-mysql
    - php8.2-xml
    - php8.2-xmlrpc
    - php8.2-curl
    - php8.2-gd
    - php8.2-imagick
    - php8.2-cli
    - php8.2-dev
    - php8.2-imap
    - php8.2-mbstring
    - php8.2-opcache
    - php8.2-soap
    - php8.2-zip

- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  loop:
    - rewrite
  when: item != 'php8.2'

- name: Restart Apache2
  service:
    name: apache2
    state: restarted

