---
- name: Upload the config file
  copy:
    src: index.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0755
  become: true

- name: Upload the config file
  copy:
    src: todo_list.php
    dest: /var/www/html/todo_list.php
    owner: root
    group: root
    mode: 0755
  become: true
