---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MySQL packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - mysql-server
    - python3-mysqldb

- name: Set MySQL root password
  mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"
    host: localhost

- name: Ensure MySQL service is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes
