---
- name: Upload the config file
  copy:
    src: create_table.sql
    dest: /tmp/create_table.sql
    owner: root
    group: root
    mode: 0755
  become: true

- name: Upload the config file
  copy:
    src: insert_record.sql
    dest: /tmp/insert_record.sql
    owner: root
    group: root
    mode: 0755
  become: true