version: '3.8'
services:
  apache:
    image: httpd:latest
    ports:
      - "80:80"
    volumes:
      - /root/github/eindopdracht:/usr/local/apache2/htdocs

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: jesseeline42
