version: '3.8'
services:
  apache:
    image: php:8-apache
    ports:
      - "80:80"
    volumes:
      - /root/github/eindopdracht:/var/www/html/
    # volumes:
    #   - /root/github/eindopdracht:/usr/local/apache2/htdocs
