- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present
    update_cache: yes

- name: Copy Fail2Ban configuration
  ansible.builtin.template:
    src: jail.local.j2
    dest: "{{ fail2ban_config_file }}"
    owner: root
    group: root
    mode: '0644'
  notify:
    - restart fail2ban

- name: Ensure Fail2Ban is started and enabled
  ansible.builtin.service:
    name: "{{ fail2ban_service_name }}"
    state: started
    enabled: yes
