- name: Maakt alle gebruikers aan van hubo-it
  include_tasks: hubo-user.yaml

- name: Maakt alle nodige directiets aan
  include_tasks: dir.yaml

- name: Auto-update
  include_tasks: auto-update.yaml

- name: auto-backup
  include_tasks: auto-backup.yaml

- name: install NTP
  include_tasks: ntp.yaml

- name: install fail2ban
  include_tasks: fail2ban.yaml

- name: configure sshd
  include_tasks: ssh.yaml
